version: "3.9"
services:
  miriconf-backend:
    build: ../.
    environment:
      MONGO_URI: "mongodb://root:testing@miriconf-backend-mongo-1:27017"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
      MONGO_INITDB_DATABASE: miriconf