
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miriconf-backend
  namespace: default
  labels:
    app: miriconf-backend
spec:
  selector:
    matchLabels:
      app: miriconf-backend
  template:
    metadata:
      labels:
        app: miriconf-backend
    spec:
      containers:
      - name: miriconf-backend
        image: miriconf-backend
        env:
        - name: MONGO_URI
          value: "mongodb://admin:localdev@mongo-svc.default.svc.cluster.local/admin?ssl=false"
      ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: miriconf-backend
  ports:
    - protocol: TCP
      port: 8081
