
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miriconf-backend
  namespace: default
  labels:
    app: miriconf-backend
spec:
  selector:
    matchLabels:
      app: miriconf-backend
  template:
    metadata:
      labels:
        app: miriconf-backend
    spec:
      containers:
      - name: miriconf-backend
        image: miriconf-backend
        env:
        - name: MONGO_URI
          value: "mongodb+srv://admin:localdev@mongodb-svc.default.svc.cluster.local/?replicaSet=mongodb&ssl=false"
      ports:
        - containerPort: 8081
