
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miriconf-backend
  namespace: default
  labels:
    app: miriconf-backend
spec:
  selector:
    matchLabels:
      app: miriconf-backend
  template:
    metadata:
      labels:
        app: miriconf-backend
    spec:
      containers:
      - name: miriconf-backend
        image: miriconf-backend
        env:
        - name: MONGO_URI
          value: "http://mongodb.default.svc.cluster.local.:27017"
      ports:
        - containerPort: 8081
