apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  namespace: default
spec:
  containers:
  - image: mongo-express
    name: mongo-express
    ports:
     - containerPort: 8081
    env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: admin
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: localdev
    - name: ME_CONFIG_MONGODB_URL
      value: mongodb://admin:localdev@mongo-svc.default.svc.cluster.local:27017/admin?ssl=false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
